version: "3"
services:
  web:
    build: .
    volumes:
      - .:/home/node/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://data
      - NODE_ENV=production
      - PORT=8000

  redis:
    image: redis:alpine
    container_name: data
    volumes:
      - ./redis-data:/data
